//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boyfriend {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Boyfriend.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many mentions in 1 message.
        /// </summary>
        internal static string AutobanReason {
            get {
                return ResourceManager.GetString("AutobanReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :white_check_mark: Successfully banned {0} for {1}.
        /// </summary>
        internal static string BanResponse {
            get {
                return ResourceManager.GetString("BanResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bah! .
        /// </summary>
        internal static string Beep1 {
            get {
                return ResourceManager.GetString("Beep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bop! .
        /// </summary>
        internal static string Beep2 {
            get {
                return ResourceManager.GetString("Beep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beep! .
        /// </summary>
        internal static string Beep3 {
            get {
                return ResourceManager.GetString("Beep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted message from {0} in channel .
        /// </summary>
        internal static string CachedMessageDeleted {
            get {
                return ResourceManager.GetString("CachedMessageDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message edited from {0} in channel {1}.{2}Before:{3}{4}{5}After:{6}{7}.
        /// </summary>
        internal static string CachedMessageEdited {
            get {
                return ResourceManager.GetString("CachedMessageEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I cannot use time-outs on other bots! Try to set a mute role in settings.
        /// </summary>
        internal static string CannotTimeOutBot {
            get {
                return ResourceManager.GetString("CannotTimeOutBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not specified.
        /// </summary>
        internal static string ChannelNotSpecified {
            get {
                return ResourceManager.GetString("ChannelNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many messages specified!.
        /// </summary>
        internal static string ClearAmountTooLarge {
            get {
                return ResourceManager.GetString("ClearAmountTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid message amount specified!.
        /// </summary>
        internal static string ClearInvalidAmountSpecified {
            get {
                return ResourceManager.GetString("ClearInvalidAmountSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative message amount specified!.
        /// </summary>
        internal static string ClearNegativeAmount {
            get {
                return ResourceManager.GetString("ClearNegativeAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command help:{0}.
        /// </summary>
        internal static string CommandHelp {
            get {
                return ResourceManager.GetString("CommandHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I do not have permission to execute this command!.
        /// </summary>
        internal static string CommandNoPermissionBot {
            get {
                return ResourceManager.GetString("CommandNoPermissionBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to execute this command!.
        /// </summary>
        internal static string CommandNoPermissionUser {
            get {
                return ResourceManager.GetString("CommandNoPermissionUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find guild by message!.
        /// </summary>
        internal static string CouldntFindGuildByChannel {
            get {
                return ResourceManager.GetString("CouldntFindGuildByChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current settings:{0}.
        /// </summary>
        internal static string CurrentSettings {
            get {
                return ResourceManager.GetString("CurrentSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin log channel (`adminLogChannel`): {0}{1}.
        /// </summary>
        internal static string CurrentSettingsAdminLogChannel {
            get {
                return ResourceManager.GetString("CurrentSettingsAdminLogChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot log channel (`botLogChannel`): {0}.
        /// </summary>
        internal static string CurrentSettingsBotLogChannel {
            get {
                return ResourceManager.GetString("CurrentSettingsBotLogChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default role (`defaultRole`): {0}{1}.
        /// </summary>
        internal static string CurrentSettingsDefaultRole {
            get {
                return ResourceManager.GetString("CurrentSettingsDefaultRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language (`lang`): `{0}`{1}.
        /// </summary>
        internal static string CurrentSettingsLang {
            get {
                return ResourceManager.GetString("CurrentSettingsLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute role (`muteRole`): {0}{1}.
        /// </summary>
        internal static string CurrentSettingsMuteRole {
            get {
                return ResourceManager.GetString("CurrentSettingsMuteRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix (`prefix`): `{0}`{1}.
        /// </summary>
        internal static string CurrentSettingsPrefix {
            get {
                return ResourceManager.GetString("CurrentSettingsPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive startup messages (`receiveStartupMessages`): {0}{1}.
        /// </summary>
        internal static string CurrentSettingsReceiveStartupMessages {
            get {
                return ResourceManager.GetString("CurrentSettingsReceiveStartupMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove roles on mute (`removeRolesOnMute`): {0}{1}.
        /// </summary>
        internal static string CurrentSettingsRemoveRoles {
            get {
                return ResourceManager.GetString("CurrentSettingsRemoveRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send welcome messages (`sendWelcomeMessages`): {0}{1}.
        /// </summary>
        internal static string CurrentSettingsSendWelcomeMessages {
            get {
                return ResourceManager.GetString("CurrentSettingsSendWelcomeMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use system channel for notifications (`useSystemChannel`): {0}{1}.
        /// </summary>
        internal static string CurrentSettingsUseSystemChannel {
            get {
                return ResourceManager.GetString("CurrentSettingsUseSystemChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome message: `{0}`{1}.
        /// </summary>
        internal static string CurrentSettingsWelcomeMessage {
            get {
                return ResourceManager.GetString("CurrentSettingsWelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, welcome to {1}.
        /// </summary>
        internal static string DefaultWelcomeMessage {
            get {
                return ResourceManager.GetString("DefaultWelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I couldn&apos;t parse the specified duration! One of the components could be outside it&apos;s valid range (e.g. `24h` or `60m`).
        /// </summary>
        internal static string DurationParseFailed {
            get {
                return ResourceManager.GetString("DurationParseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I cannot mute someone forever using timeouts! Either specify a proper duration, or set a mute role in settings.
        /// </summary>
        internal static string DurationRequiredForTimeOuts {
            get {
                return ResourceManager.GetString("DurationRequiredForTimeOuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members are in different guilds!.
        /// </summary>
        internal static string InteractionsDifferentGuilds {
            get {
                return ResourceManager.GetString("InteractionsDifferentGuilds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I cannot interact with this member!.
        /// </summary>
        internal static string InteractionsFailedBot {
            get {
                return ResourceManager.GetString("InteractionsFailedBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot interact with this member!.
        /// </summary>
        internal static string InteractionsFailedUser {
            get {
                return ResourceManager.GetString("InteractionsFailedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot interact with me!.
        /// </summary>
        internal static string InteractionsMe {
            get {
                return ResourceManager.GetString("InteractionsMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot interact with guild owner!.
        /// </summary>
        internal static string InteractionsOwner {
            get {
                return ResourceManager.GetString("InteractionsOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot interact with yourself!.
        /// </summary>
        internal static string InteractionsYourself {
            get {
                return ResourceManager.GetString("InteractionsYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This channel does not exist!.
        /// </summary>
        internal static string InvalidChannel {
            get {
                return ResourceManager.GetString("InvalidChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This role does not exist!.
        /// </summary>
        internal static string InvalidRole {
            get {
                return ResourceManager.GetString("InvalidRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid setting value specified!.
        /// </summary>
        internal static string InvalidSettingValue {
            get {
                return ResourceManager.GetString("InvalidSettingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :white_check_mark: Successfully kicked {0} for {1}.
        /// </summary>
        internal static string KickResponse {
            get {
                return ResourceManager.GetString("KickResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language not supported!.
        /// </summary>
        internal static string LanguageNotSupported {
            get {
                return ResourceManager.GetString("LanguageNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member is already muted!.
        /// </summary>
        internal static string MemberAlreadyMuted {
            get {
                return ResourceManager.GetString("MemberAlreadyMuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} kicked {1} for {2}.
        /// </summary>
        internal static string MemberKicked {
            get {
                return ResourceManager.GetString("MemberKicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} muted {1} for {2}{3}.
        /// </summary>
        internal static string MemberMuted {
            get {
                return ResourceManager.GetString("MemberMuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member not muted!.
        /// </summary>
        internal static string MemberNotMuted {
            get {
                return ResourceManager.GetString("MemberNotMuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} unmuted {1} for {2}.
        /// </summary>
        internal static string MemberUnmuted {
            get {
                return ResourceManager.GetString("MemberUnmuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deleted {1} messages in channel {2}.
        /// </summary>
        internal static string MessagesDeleted {
            get {
                return ResourceManager.GetString("MessagesDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ms.
        /// </summary>
        internal static string Milliseconds {
            get {
                return ResourceManager.GetString("Milliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :white_check_mark: Successfully muted {0} for {1}.
        /// </summary>
        internal static string MuteResponse {
            get {
                return ResourceManager.GetString("MuteResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough arguments! Needed: {0}, provided: {1}.
        /// </summary>
        internal static string NotEnoughArguments {
            get {
                return ResourceManager.GetString("NotEnoughArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punishment expired.
        /// </summary>
        internal static string PunishmentExpired {
            get {
                return ResourceManager.GetString("PunishmentExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}This punishment will expire &lt;t:{1}:R&gt;.
        /// </summary>
        internal static string PunishmentExpiresIn {
            get {
                return ResourceManager.GetString("PunishmentExpiresIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}I&apos;m ready! (C#).
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not specified.
        /// </summary>
        internal static string RoleNotSpecified {
            get {
                return ResourceManager.GetString("RoleNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I couldn&apos;t remove role {0} because of an error! {1}.
        /// </summary>
        internal static string RoleRemovalFailed {
            get {
                return ResourceManager.GetString("RoleRemovalFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Someone removed the mute role manually! I added back all roles that I removed during the mute.
        /// </summary>
        internal static string RolesReturned {
            get {
                return ResourceManager.GetString("RolesReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That setting doesn&apos;t exist!.
        /// </summary>
        internal static string SettingDoesntExist {
            get {
                return ResourceManager.GetString("SettingDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings successfully updated.
        /// </summary>
        internal static string SettingsUpdated {
            get {
                return ResourceManager.GetString("SettingsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :white_check_mark: Successfully unbanned {0} for {1}.
        /// </summary>
        internal static string UnbanResponse {
            get {
                return ResourceManager.GetString("UnbanResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted message in {0}, but I forgot what was there.
        /// </summary>
        internal static string UncachedMessageDeleted {
            get {
                return ResourceManager.GetString("UncachedMessageDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message edited from {0} in channel {1}, but I forgot what was there before the edit: .
        /// </summary>
        internal static string UncachedMessageEdited {
            get {
                return ResourceManager.GetString("UncachedMessageEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :white_check_mark: Successfully unmuted {0} for {1}.
        /// </summary>
        internal static string UnmuteResponse {
            get {
                return ResourceManager.GetString("UnmuteResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} banned {1} for {2}{3}.
        /// </summary>
        internal static string UserBanned {
            get {
                return ResourceManager.GetString("UserBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not banned!.
        /// </summary>
        internal static string UserNotBanned {
            get {
                return ResourceManager.GetString("UserNotBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified user is not a member of this server!.
        /// </summary>
        internal static string UserNotInGuild {
            get {
                return ResourceManager.GetString("UserNotInGuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} unbanned {1} for {2}.
        /// </summary>
        internal static string UserUnbanned {
            get {
                return ResourceManager.GetString("UserUnbanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You were banned by {0} in guild {1} for {2}.
        /// </summary>
        internal static string YouWereBanned {
            get {
                return ResourceManager.GetString("YouWereBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You were kicked by {0} in guild {1} for {2}.
        /// </summary>
        internal static string YouWereKicked {
            get {
                return ResourceManager.GetString("YouWereKicked", resourceCulture);
            }
        }
    }
}
