//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boyfriend {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Boyfriend.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string CouldntFindGuildByChannel {
            get {
                return ResourceManager.GetString("CouldntFindGuildByChannel", resourceCulture);
            }
        }
        
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        internal static string UncachedMessageDeleted {
            get {
                return ResourceManager.GetString("UncachedMessageDeleted", resourceCulture);
            }
        }
        
        internal static string CachedMessageDeleted {
            get {
                return ResourceManager.GetString("CachedMessageDeleted", resourceCulture);
            }
        }
        
        internal static string AutobanReason {
            get {
                return ResourceManager.GetString("AutobanReason", resourceCulture);
            }
        }
        
        internal static string UncachedMessageEdited {
            get {
                return ResourceManager.GetString("UncachedMessageEdited", resourceCulture);
            }
        }
        
        internal static string CachedMessageEdited {
            get {
                return ResourceManager.GetString("CachedMessageEdited", resourceCulture);
            }
        }
        
        internal static string DefaultWelcomeMessage {
            get {
                return ResourceManager.GetString("DefaultWelcomeMessage", resourceCulture);
            }
        }
        
        internal static string Beep1 {
            get {
                return ResourceManager.GetString("Beep1", resourceCulture);
            }
        }
        
        internal static string Beep2 {
            get {
                return ResourceManager.GetString("Beep2", resourceCulture);
            }
        }
        
        internal static string Beep3 {
            get {
                return ResourceManager.GetString("Beep3", resourceCulture);
            }
        }
        
        internal static string InvalidAdminLogChannel {
            get {
                return ResourceManager.GetString("InvalidAdminLogChannel", resourceCulture);
            }
        }
        
        internal static string MuteRoleRequired {
            get {
                return ResourceManager.GetString("MuteRoleRequired", resourceCulture);
            }
        }
        
        internal static string CommandExecutionUnsuccessful {
            get {
                return ResourceManager.GetString("CommandExecutionUnsuccessful", resourceCulture);
            }
        }
        
        internal static string RepeatedArgumentsDetected {
            get {
                return ResourceManager.GetString("RepeatedArgumentsDetected", resourceCulture);
            }
        }
        
        internal static string CommandParseFailed {
            get {
                return ResourceManager.GetString("CommandParseFailed", resourceCulture);
            }
        }
        
        internal static string UnknownCommand {
            get {
                return ResourceManager.GetString("UnknownCommand", resourceCulture);
            }
        }
        
        internal static string BadArgumentCount {
            get {
                return ResourceManager.GetString("BadArgumentCount", resourceCulture);
            }
        }
        
        internal static string ArgumentNotPresent {
            get {
                return ResourceManager.GetString("ArgumentNotPresent", resourceCulture);
            }
        }
        
        internal static string CommandNoPermissionBot {
            get {
                return ResourceManager.GetString("CommandNoPermissionBot", resourceCulture);
            }
        }
        
        internal static string CommandNoPermissionUser {
            get {
                return ResourceManager.GetString("CommandNoPermissionUser", resourceCulture);
            }
        }
        
        internal static string InteractionsDifferentGuilds {
            get {
                return ResourceManager.GetString("InteractionsDifferentGuilds", resourceCulture);
            }
        }
        
        internal static string InteractionsOwner {
            get {
                return ResourceManager.GetString("InteractionsOwner", resourceCulture);
            }
        }
        
        internal static string InteractionsYourself {
            get {
                return ResourceManager.GetString("InteractionsYourself", resourceCulture);
            }
        }
        
        internal static string InteractionsMe {
            get {
                return ResourceManager.GetString("InteractionsMe", resourceCulture);
            }
        }
        
        internal static string InteractionsFailedUser {
            get {
                return ResourceManager.GetString("InteractionsFailedUser", resourceCulture);
            }
        }
        
        internal static string InteractionsFailedBot {
            get {
                return ResourceManager.GetString("InteractionsFailedBot", resourceCulture);
            }
        }
        
        internal static string YouWereBanned {
            get {
                return ResourceManager.GetString("YouWereBanned", resourceCulture);
            }
        }
        
        internal static string UserBanned {
            get {
                return ResourceManager.GetString("UserBanned", resourceCulture);
            }
        }
        
        internal static string PunishmentExpired {
            get {
                return ResourceManager.GetString("PunishmentExpired", resourceCulture);
            }
        }
        
        internal static string ClearNegativeAmount {
            get {
                return ResourceManager.GetString("ClearNegativeAmount", resourceCulture);
            }
        }
        
        internal static string ClearAmountTooLarge {
            get {
                return ResourceManager.GetString("ClearAmountTooLarge", resourceCulture);
            }
        }
        
        internal static string MessagesDeleted {
            get {
                return ResourceManager.GetString("MessagesDeleted", resourceCulture);
            }
        }
        
        internal static string CommandHelp {
            get {
                return ResourceManager.GetString("CommandHelp", resourceCulture);
            }
        }
        
        internal static string YouWereKicked {
            get {
                return ResourceManager.GetString("YouWereKicked", resourceCulture);
            }
        }
        
        internal static string MemberKicked {
            get {
                return ResourceManager.GetString("MemberKicked", resourceCulture);
            }
        }
        
        internal static string MemberMuted {
            get {
                return ResourceManager.GetString("MemberMuted", resourceCulture);
            }
        }
        
        internal static string Milliseconds {
            get {
                return ResourceManager.GetString("Milliseconds", resourceCulture);
            }
        }
        
        internal static string MemberAlreadyMuted {
            get {
                return ResourceManager.GetString("MemberAlreadyMuted", resourceCulture);
            }
        }
        
        internal static string MuteRoleManuallyRemoved {
            get {
                return ResourceManager.GetString("MuteRoleManuallyRemoved", resourceCulture);
            }
        }
        
        internal static string ChannelNotSpecified {
            get {
                return ResourceManager.GetString("ChannelNotSpecified", resourceCulture);
            }
        }
        
        internal static string RoleNotSpecified {
            get {
                return ResourceManager.GetString("RoleNotSpecified", resourceCulture);
            }
        }
        
        internal static string CurrentSettings {
            get {
                return ResourceManager.GetString("CurrentSettings", resourceCulture);
            }
        }
        
        internal static string CurrentSettingsLang {
            get {
                return ResourceManager.GetString("CurrentSettingsLang", resourceCulture);
            }
        }
        
        internal static string CurrentSettingsPrefix {
            get {
                return ResourceManager.GetString("CurrentSettingsPrefix", resourceCulture);
            }
        }
        
        internal static string CurrentSettingsRemoveRoles {
            get {
                return ResourceManager.GetString("CurrentSettingsRemoveRoles", resourceCulture);
            }
        }
        
        internal static string CurrentSettingsUseSystemChannel {
            get {
                return ResourceManager.GetString("CurrentSettingsUseSystemChannel", resourceCulture);
            }
        }
        
        internal static string CurrentSettingsSendWelcomeMessages {
            get {
                return ResourceManager.GetString("CurrentSettingsSendWelcomeMessages", resourceCulture);
            }
        }
        
        internal static string CurrentSettingsDefaultRole {
            get {
                return ResourceManager.GetString("CurrentSettingsDefaultRole", resourceCulture);
            }
        }
        
        internal static string CurrentSettingsMuteRole {
            get {
                return ResourceManager.GetString("CurrentSettingsMuteRole", resourceCulture);
            }
        }
        
        internal static string CurrentSettingsAdminLogChannel {
            get {
                return ResourceManager.GetString("CurrentSettingsAdminLogChannel", resourceCulture);
            }
        }
        
        internal static string CurrentSettingsBotLogChannel {
            get {
                return ResourceManager.GetString("CurrentSettingsBotLogChannel", resourceCulture);
            }
        }
        
        internal static string LanguageNotSupported {
            get {
                return ResourceManager.GetString("LanguageNotSupported", resourceCulture);
            }
        }
        
        internal static string SettingsUpdated {
            get {
                return ResourceManager.GetString("SettingsUpdated", resourceCulture);
            }
        }
        
        internal static string InvalidBoolean {
            get {
                return ResourceManager.GetString("InvalidBoolean", resourceCulture);
            }
        }
        
        internal static string InvalidRoleSpecified {
            get {
                return ResourceManager.GetString("InvalidRoleSpecified", resourceCulture);
            }
        }
        
        internal static string InvalidChannelSpecified {
            get {
                return ResourceManager.GetString("InvalidChannelSpecified", resourceCulture);
            }
        }
        
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        internal static string UserNotBanned {
            get {
                return ResourceManager.GetString("UserNotBanned", resourceCulture);
            }
        }
        
        internal static string MemberNotMuted {
            get {
                return ResourceManager.GetString("MemberNotMuted", resourceCulture);
            }
        }
        
        internal static string RolesReturned {
            get {
                return ResourceManager.GetString("RolesReturned", resourceCulture);
            }
        }
        
        internal static string MemberUnmuted {
            get {
                return ResourceManager.GetString("MemberUnmuted", resourceCulture);
            }
        }
        
        internal static string UserUnbanned {
            get {
                return ResourceManager.GetString("UserUnbanned", resourceCulture);
            }
        }
        
        internal static string CurrentSettingsWelcomeMessage {
            get {
                return ResourceManager.GetString("CurrentSettingsWelcomeMessage", resourceCulture);
            }
        }
        
        internal static string NotEnoughArguments {
            get {
                return ResourceManager.GetString("NotEnoughArguments", resourceCulture);
            }
        }
        
        internal static string ClearInvalidAmountSpecified {
            get {
                return ResourceManager.GetString("ClearInvalidAmountSpecified", resourceCulture);
            }
        }
        
        internal static string BanResponse {
            get {
                return ResourceManager.GetString("BanResponse", resourceCulture);
            }
        }
        
        internal static string KickResponse {
            get {
                return ResourceManager.GetString("KickResponse", resourceCulture);
            }
        }
        
        internal static string UserNotInGuild {
            get {
                return ResourceManager.GetString("UserNotInGuild", resourceCulture);
            }
        }
        
        internal static string MuteResponse {
            get {
                return ResourceManager.GetString("MuteResponse", resourceCulture);
            }
        }
        
        internal static string UnbanResponse {
            get {
                return ResourceManager.GetString("UnbanResponse", resourceCulture);
            }
        }
        
        internal static string UnmuteResponse {
            get {
                return ResourceManager.GetString("UnmuteResponse", resourceCulture);
            }
        }
    }
}
