//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boyfriend {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Boyfriend.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string CouldntFindGuildByChannel {
            get {
                return ResourceManager.GetString("CouldntFindGuildByChannel", resourceCulture);
            }
        }
        
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        internal static string UncachedMessageDeleted {
            get {
                return ResourceManager.GetString("UncachedMessageDeleted", resourceCulture);
            }
        }
        
        internal static string CachedMessageDeleted {
            get {
                return ResourceManager.GetString("CachedMessageDeleted", resourceCulture);
            }
        }
        
        internal static string AutobanReason {
            get {
                return ResourceManager.GetString("AutobanReason", resourceCulture);
            }
        }
        
        internal static string UncachedMessageEdited {
            get {
                return ResourceManager.GetString("UncachedMessageEdited", resourceCulture);
            }
        }
        
        internal static string CachedMessageEdited {
            get {
                return ResourceManager.GetString("CachedMessageEdited", resourceCulture);
            }
        }
        
        internal static string DefaultWelcomeMessage {
            get {
                return ResourceManager.GetString("DefaultWelcomeMessage", resourceCulture);
            }
        }
        
        internal static string Beep1 {
            get {
                return ResourceManager.GetString("Beep1", resourceCulture);
            }
        }
        
        internal static string Beep2 {
            get {
                return ResourceManager.GetString("Beep2", resourceCulture);
            }
        }
        
        internal static string Beep3 {
            get {
                return ResourceManager.GetString("Beep3", resourceCulture);
            }
        }
        
        internal static string CommandNoPermissionBot {
            get {
                return ResourceManager.GetString("CommandNoPermissionBot", resourceCulture);
            }
        }
        
        internal static string CommandNoPermissionUser {
            get {
                return ResourceManager.GetString("CommandNoPermissionUser", resourceCulture);
            }
        }
        
        internal static string InteractionsDifferentGuilds {
            get {
                return ResourceManager.GetString("InteractionsDifferentGuilds", resourceCulture);
            }
        }
        
        internal static string InteractionsOwner {
            get {
                return ResourceManager.GetString("InteractionsOwner", resourceCulture);
            }
        }
        
        internal static string InteractionsYourself {
            get {
                return ResourceManager.GetString("InteractionsYourself", resourceCulture);
            }
        }
        
        internal static string InteractionsMe {
            get {
                return ResourceManager.GetString("InteractionsMe", resourceCulture);
            }
        }
        
        internal static string InteractionsFailedUser {
            get {
                return ResourceManager.GetString("InteractionsFailedUser", resourceCulture);
            }
        }
        
        internal static string InteractionsFailedBot {
            get {
                return ResourceManager.GetString("InteractionsFailedBot", resourceCulture);
            }
        }
        
        internal static string YouWereBanned {
            get {
                return ResourceManager.GetString("YouWereBanned", resourceCulture);
            }
        }
        
        internal static string PunishmentExpired {
            get {
                return ResourceManager.GetString("PunishmentExpired", resourceCulture);
            }
        }
        
        internal static string ClearNegativeAmount {
            get {
                return ResourceManager.GetString("ClearNegativeAmount", resourceCulture);
            }
        }
        
        internal static string ClearAmountTooLarge {
            get {
                return ResourceManager.GetString("ClearAmountTooLarge", resourceCulture);
            }
        }
        
        internal static string CommandHelp {
            get {
                return ResourceManager.GetString("CommandHelp", resourceCulture);
            }
        }
        
        internal static string YouWereKicked {
            get {
                return ResourceManager.GetString("YouWereKicked", resourceCulture);
            }
        }
        
        internal static string Milliseconds {
            get {
                return ResourceManager.GetString("Milliseconds", resourceCulture);
            }
        }
        
        internal static string MemberAlreadyMuted {
            get {
                return ResourceManager.GetString("MemberAlreadyMuted", resourceCulture);
            }
        }
        
        internal static string ChannelNotSpecified {
            get {
                return ResourceManager.GetString("ChannelNotSpecified", resourceCulture);
            }
        }
        
        internal static string RoleNotSpecified {
            get {
                return ResourceManager.GetString("RoleNotSpecified", resourceCulture);
            }
        }
        
        internal static string CurrentSettings {
            get {
                return ResourceManager.GetString("CurrentSettings", resourceCulture);
            }
        }
        
        internal static string SettingsLang {
            get {
                return ResourceManager.GetString("SettingsLang", resourceCulture);
            }
        }
        
        internal static string SettingsPrefix {
            get {
                return ResourceManager.GetString("SettingsPrefix", resourceCulture);
            }
        }
        
        internal static string SettingsRemoveRolesOnMute {
            get {
                return ResourceManager.GetString("SettingsRemoveRolesOnMute", resourceCulture);
            }
        }
        
        internal static string SettingsSendWelcomeMessages {
            get {
                return ResourceManager.GetString("SettingsSendWelcomeMessages", resourceCulture);
            }
        }
        
        internal static string SettingsStarterRole {
            get {
                return ResourceManager.GetString("SettingsStarterRole", resourceCulture);
            }
        }
        
        internal static string SettingsMuteRole {
            get {
                return ResourceManager.GetString("SettingsMuteRole", resourceCulture);
            }
        }
        
        internal static string SettingsAdminLogChannel {
            get {
                return ResourceManager.GetString("SettingsAdminLogChannel", resourceCulture);
            }
        }
        
        internal static string SettingsBotLogChannel {
            get {
                return ResourceManager.GetString("SettingsBotLogChannel", resourceCulture);
            }
        }
        
        internal static string LanguageNotSupported {
            get {
                return ResourceManager.GetString("LanguageNotSupported", resourceCulture);
            }
        }
        
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        internal static string UserNotBanned {
            get {
                return ResourceManager.GetString("UserNotBanned", resourceCulture);
            }
        }
        
        internal static string MemberNotMuted {
            get {
                return ResourceManager.GetString("MemberNotMuted", resourceCulture);
            }
        }
        
        internal static string RolesReturned {
            get {
                return ResourceManager.GetString("RolesReturned", resourceCulture);
            }
        }
        
        internal static string MemberUnmuted {
            get {
                return ResourceManager.GetString("MemberUnmuted", resourceCulture);
            }
        }
        
        internal static string UserUnbanned {
            get {
                return ResourceManager.GetString("UserUnbanned", resourceCulture);
            }
        }
        
        internal static string SettingsWelcomeMessage {
            get {
                return ResourceManager.GetString("SettingsWelcomeMessage", resourceCulture);
            }
        }
        
        internal static string NotEnoughArguments {
            get {
                return ResourceManager.GetString("NotEnoughArguments", resourceCulture);
            }
        }
        
        internal static string ClearInvalidAmountSpecified {
            get {
                return ResourceManager.GetString("ClearInvalidAmountSpecified", resourceCulture);
            }
        }
        
        internal static string FeedbackUserBanned {
            get {
                return ResourceManager.GetString("FeedbackUserBanned", resourceCulture);
            }
        }
        
        internal static string UserNotInGuild {
            get {
                return ResourceManager.GetString("UserNotInGuild", resourceCulture);
            }
        }
        
        internal static string SettingDoesntExist {
            get {
                return ResourceManager.GetString("SettingDoesntExist", resourceCulture);
            }
        }
        
        internal static string SettingsReceiveStartupMessages {
            get {
                return ResourceManager.GetString("SettingsReceiveStartupMessages", resourceCulture);
            }
        }
        
        internal static string InvalidSettingValue {
            get {
                return ResourceManager.GetString("InvalidSettingValue", resourceCulture);
            }
        }
        
        internal static string InvalidRole {
            get {
                return ResourceManager.GetString("InvalidRole", resourceCulture);
            }
        }
        
        internal static string InvalidChannel {
            get {
                return ResourceManager.GetString("InvalidChannel", resourceCulture);
            }
        }
        
        internal static string DurationParseFailed {
            get {
                return ResourceManager.GetString("DurationParseFailed", resourceCulture);
            }
        }
        
        internal static string RoleRemovalFailed {
            get {
                return ResourceManager.GetString("RoleRemovalFailed", resourceCulture);
            }
        }
        
        internal static string DurationRequiredForTimeOuts {
            get {
                return ResourceManager.GetString("DurationRequiredForTimeOuts", resourceCulture);
            }
        }
        
        internal static string CannotTimeOutBot {
            get {
                return ResourceManager.GetString("CannotTimeOutBot", resourceCulture);
            }
        }
        
        internal static string EventCreated {
            get {
                return ResourceManager.GetString("EventCreated", resourceCulture);
            }
        }
        
        internal static string SettingsEventNotifyReceiverRole {
            get {
                return ResourceManager.GetString("SettingsEventNotifyReceiverRole", resourceCulture);
            }
        }
        
        internal static string SettingsEventCreatedChannel {
            get {
                return ResourceManager.GetString("SettingsEventCreatedChannel", resourceCulture);
            }
        }
        
        internal static string SettingsEventStartedChannel {
            get {
                return ResourceManager.GetString("SettingsEventStartedChannel", resourceCulture);
            }
        }
        
        internal static string SettingsEventStartedReceivers {
            get {
                return ResourceManager.GetString("SettingsEventStartedReceivers", resourceCulture);
            }
        }
        
        internal static string EventStarted {
            get {
                return ResourceManager.GetString("EventStarted", resourceCulture);
            }
        }
        
        internal static string SettingsFrowningFace {
            get {
                return ResourceManager.GetString("SettingsFrowningFace", resourceCulture);
            }
        }
        
        internal static string EventCancelled {
            get {
                return ResourceManager.GetString("EventCancelled", resourceCulture);
            }
        }
        
        internal static string SettingsEventCancelledChannel {
            get {
                return ResourceManager.GetString("SettingsEventCancelledChannel", resourceCulture);
            }
        }
        
        internal static string SettingsEventCompletedChannel {
            get {
                return ResourceManager.GetString("SettingsEventCompletedChannel", resourceCulture);
            }
        }
        
        internal static string EventCompleted {
            get {
                return ResourceManager.GetString("EventCompleted", resourceCulture);
            }
        }
        
        internal static string UserDoesntExist {
            get {
                return ResourceManager.GetString("UserDoesntExist", resourceCulture);
            }
        }
        
        internal static string FeedbackFormat {
            get {
                return ResourceManager.GetString("FeedbackFormat", resourceCulture);
            }
        }
        
        internal static string Ever {
            get {
                return ResourceManager.GetString("Ever", resourceCulture);
            }
        }
        
        internal static string FeedbackMessagesCleared {
            get {
                return ResourceManager.GetString("FeedbackMessagesCleared", resourceCulture);
            }
        }
        
        internal static string FeedbackMemberKicked {
            get {
                return ResourceManager.GetString("FeedbackMemberKicked", resourceCulture);
            }
        }
        
        internal static string FeedbackMemberMuted {
            get {
                return ResourceManager.GetString("FeedbackMemberMuted", resourceCulture);
            }
        }
        
        internal static string FeedbackUserUnbanned {
            get {
                return ResourceManager.GetString("FeedbackUserUnbanned", resourceCulture);
            }
        }
        
        internal static string FeedbackMemberUnmuted {
            get {
                return ResourceManager.GetString("FeedbackMemberUnmuted", resourceCulture);
            }
        }
        
        internal static string SettingsNothingChanged {
            get {
                return ResourceManager.GetString("SettingsNothingChanged", resourceCulture);
            }
        }
        
        internal static string SettingNotDefined {
            get {
                return ResourceManager.GetString("SettingNotDefined", resourceCulture);
            }
        }
        
        internal static string FeedbackSettingsUpdated {
            get {
                return ResourceManager.GetString("FeedbackSettingsUpdated", resourceCulture);
            }
        }
        
        internal static string CommandDescriptionBan {
            get {
                return ResourceManager.GetString("CommandDescriptionBan", resourceCulture);
            }
        }
        
        internal static string CommandDescriptionClear {
            get {
                return ResourceManager.GetString("CommandDescriptionClear", resourceCulture);
            }
        }
        
        internal static string CommandDescriptionHelp {
            get {
                return ResourceManager.GetString("CommandDescriptionHelp", resourceCulture);
            }
        }
        
        internal static string CommandDescriptionKick {
            get {
                return ResourceManager.GetString("CommandDescriptionKick", resourceCulture);
            }
        }
        
        internal static string CommandDescriptionMute {
            get {
                return ResourceManager.GetString("CommandDescriptionMute", resourceCulture);
            }
        }
        
        internal static string CommandDescriptionPing {
            get {
                return ResourceManager.GetString("CommandDescriptionPing", resourceCulture);
            }
        }
        
        internal static string CommandDescriptionSettings {
            get {
                return ResourceManager.GetString("CommandDescriptionSettings", resourceCulture);
            }
        }
        
        internal static string CommandDescriptionUnban {
            get {
                return ResourceManager.GetString("CommandDescriptionUnban", resourceCulture);
            }
        }
        
        internal static string CommandDescriptionUnmute {
            get {
                return ResourceManager.GetString("CommandDescriptionUnmute", resourceCulture);
            }
        }
        
        internal static string ReasonRequired {
            get {
                return ResourceManager.GetString("ReasonRequired", resourceCulture);
            }
        }
    }
}
