//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Octobot {
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Octobot.locale.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }

        internal static string CachedMessageDeleted {
            get {
                return ResourceManager.GetString("CachedMessageDeleted", resourceCulture);
            }
        }

        internal static string CachedMessageEdited {
            get {
                return ResourceManager.GetString("CachedMessageEdited", resourceCulture);
            }
        }

        internal static string DefaultWelcomeMessage {
            get {
                return ResourceManager.GetString("DefaultWelcomeMessage", resourceCulture);
            }
        }

        internal static string Sound1 {
            get {
                return ResourceManager.GetString("Sound1", resourceCulture);
            }
        }

        internal static string Sound2 {
            get {
                return ResourceManager.GetString("Sound2", resourceCulture);
            }
        }

        internal static string Sound3 {
            get {
                return ResourceManager.GetString("Sound3", resourceCulture);
            }
        }

        internal static string YouWereBanned {
            get {
                return ResourceManager.GetString("YouWereBanned", resourceCulture);
            }
        }

        internal static string PunishmentExpired {
            get {
                return ResourceManager.GetString("PunishmentExpired", resourceCulture);
            }
        }

        internal static string YouWereKicked {
            get {
                return ResourceManager.GetString("YouWereKicked", resourceCulture);
            }
        }

        internal static string Milliseconds {
            get {
                return ResourceManager.GetString("Milliseconds", resourceCulture);
            }
        }

        internal static string ChannelNotSpecified {
            get {
                return ResourceManager.GetString("ChannelNotSpecified", resourceCulture);
            }
        }

        internal static string RoleNotSpecified {
            get {
                return ResourceManager.GetString("RoleNotSpecified", resourceCulture);
            }
        }

        internal static string SettingsLang {
            get {
                return ResourceManager.GetString("SettingsLang", resourceCulture);
            }
        }

        internal static string SettingsPrefix {
            get {
                return ResourceManager.GetString("SettingsPrefix", resourceCulture);
            }
        }

        internal static string SettingsRemoveRolesOnMute {
            get {
                return ResourceManager.GetString("SettingsRemoveRolesOnMute", resourceCulture);
            }
        }

        internal static string SettingsSendWelcomeMessages {
            get {
                return ResourceManager.GetString("SettingsSendWelcomeMessages", resourceCulture);
            }
        }

        internal static string SettingsMuteRole {
            get {
                return ResourceManager.GetString("SettingsMuteRole", resourceCulture);
            }
        }

        internal static string LanguageNotSupported {
            get {
                return ResourceManager.GetString("LanguageNotSupported", resourceCulture);
            }
        }

        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }

        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }

        internal static string UserNotBanned {
            get {
                return ResourceManager.GetString("UserNotBanned", resourceCulture);
            }
        }

        internal static string MemberNotMuted {
            get {
                return ResourceManager.GetString("MemberNotMuted", resourceCulture);
            }
        }

        internal static string SettingsWelcomeMessage {
            get {
                return ResourceManager.GetString("SettingsWelcomeMessage", resourceCulture);
            }
        }

        internal static string UserBanned {
            get {
                return ResourceManager.GetString("UserBanned", resourceCulture);
            }
        }

        internal static string SettingsReceiveStartupMessages {
            get {
                return ResourceManager.GetString("SettingsReceiveStartupMessages", resourceCulture);
            }
        }

        internal static string InvalidSettingValue {
            get {
                return ResourceManager.GetString("InvalidSettingValue", resourceCulture);
            }
        }

        internal static string InvalidRole {
            get {
                return ResourceManager.GetString("InvalidRole", resourceCulture);
            }
        }

        internal static string InvalidChannel {
            get {
                return ResourceManager.GetString("InvalidChannel", resourceCulture);
            }
        }

        internal static string DurationRequiredForTimeOuts {
            get {
                return ResourceManager.GetString("DurationRequiredForTimeOuts", resourceCulture);
            }
        }

        internal static string CannotTimeOutBot {
            get {
                return ResourceManager.GetString("CannotTimeOutBot", resourceCulture);
            }
        }

        internal static string SettingsEventNotificationRole {
            get {
                return ResourceManager.GetString("SettingsEventNotificationRole", resourceCulture);
            }
        }

        internal static string SettingsEventNotificationChannel {
            get {
                return ResourceManager.GetString("SettingsEventNotificationChannel", resourceCulture);
            }
        }

        internal static string SettingsEventStartedReceivers {
            get {
                return ResourceManager.GetString("SettingsEventStartedReceivers", resourceCulture);
            }
        }

        internal static string EventStarted {
            get {
                return ResourceManager.GetString("EventStarted", resourceCulture);
            }
        }

        internal static string EventCancelled {
            get {
                return ResourceManager.GetString("EventCancelled", resourceCulture);
            }
        }

        internal static string EventCompleted {
            get {
                return ResourceManager.GetString("EventCompleted", resourceCulture);
            }
        }

        internal static string MessagesCleared {
            get {
                return ResourceManager.GetString("MessagesCleared", resourceCulture);
            }
        }

        internal static string SettingsNothingChanged {
            get {
                return ResourceManager.GetString("SettingsNothingChanged", resourceCulture);
            }
        }

        internal static string SettingNotDefined {
            get {
                return ResourceManager.GetString("SettingNotDefined", resourceCulture);
            }
        }

        internal static string UserCannotBanMembers {
            get {
                return ResourceManager.GetString("UserCannotBanMembers", resourceCulture);
            }
        }

        internal static string UserCannotManageMessages {
            get {
                return ResourceManager.GetString("UserCannotManageMessages", resourceCulture);
            }
        }

        internal static string UserCannotKickMembers {
            get {
                return ResourceManager.GetString("UserCannotKickMembers", resourceCulture);
            }
        }

        internal static string UserCannotModerateMembers {
            get {
                return ResourceManager.GetString("UserCannotModerateMembers", resourceCulture);
            }
        }

        internal static string UserCannotManageGuild {
            get {
                return ResourceManager.GetString("UserCannotManageGuild", resourceCulture);
            }
        }

        internal static string BotCannotBanMembers {
            get {
                return ResourceManager.GetString("BotCannotBanMembers", resourceCulture);
            }
        }

        internal static string BotCannotManageMessages {
            get {
                return ResourceManager.GetString("BotCannotManageMessages", resourceCulture);
            }
        }

        internal static string BotCannotKickMembers {
            get {
                return ResourceManager.GetString("BotCannotKickMembers", resourceCulture);
            }
        }

        internal static string BotCannotModerateMembers {
            get {
                return ResourceManager.GetString("BotCannotModerateMembers", resourceCulture);
            }
        }

        internal static string BotCannotManageGuild {
            get {
                return ResourceManager.GetString("BotCannotManageGuild", resourceCulture);
            }
        }

        internal static string UserCannotBanOwner {
            get {
                return ResourceManager.GetString("UserCannotBanOwner", resourceCulture);
            }
        }

        internal static string UserCannotBanThemselves {
            get {
                return ResourceManager.GetString("UserCannotBanThemselves", resourceCulture);
            }
        }

        internal static string UserCannotBanBot {
            get {
                return ResourceManager.GetString("UserCannotBanBot", resourceCulture);
            }
        }

        internal static string BotCannotBanTarget {
            get {
                return ResourceManager.GetString("BotCannotBanTarget", resourceCulture);
            }
        }

        internal static string UserCannotBanTarget {
            get {
                return ResourceManager.GetString("UserCannotBanTarget", resourceCulture);
            }
        }

        internal static string UserCannotKickOwner {
            get {
                return ResourceManager.GetString("UserCannotKickOwner", resourceCulture);
            }
        }

        internal static string UserCannotKickThemselves {
            get {
                return ResourceManager.GetString("UserCannotKickThemselves", resourceCulture);
            }
        }

        internal static string UserCannotKickBot {
            get {
                return ResourceManager.GetString("UserCannotKickBot", resourceCulture);
            }
        }

        internal static string BotCannotKickTarget {
            get {
                return ResourceManager.GetString("BotCannotKickTarget", resourceCulture);
            }
        }

        internal static string UserCannotKickTarget {
            get {
                return ResourceManager.GetString("UserCannotKickTarget", resourceCulture);
            }
        }

        internal static string UserCannotMuteOwner {
            get {
                return ResourceManager.GetString("UserCannotMuteOwner", resourceCulture);
            }
        }

        internal static string UserCannotMuteThemselves {
            get {
                return ResourceManager.GetString("UserCannotMuteThemselves", resourceCulture);
            }
        }

        internal static string UserCannotMuteBot {
            get {
                return ResourceManager.GetString("UserCannotMuteBot", resourceCulture);
            }
        }

        internal static string BotCannotMuteTarget {
            get {
                return ResourceManager.GetString("BotCannotMuteTarget", resourceCulture);
            }
        }

        internal static string UserCannotMuteTarget {
            get {
                return ResourceManager.GetString("UserCannotMuteTarget", resourceCulture);
            }
        }

        internal static string UserCannotUnmuteOwner {
            get {
                return ResourceManager.GetString("UserCannotUnmuteOwner", resourceCulture);
            }
        }

        internal static string UserCannotUnmuteThemselves {
            get {
                return ResourceManager.GetString("UserCannotUnmuteThemselves", resourceCulture);
            }
        }

        internal static string UserCannotUnmuteBot {
            get {
                return ResourceManager.GetString("UserCannotUnmuteBot", resourceCulture);
            }
        }

        internal static string BotCannotUnmuteTarget {
            get {
                return ResourceManager.GetString("BotCannotUnmuteTarget", resourceCulture);
            }
        }

        internal static string UserCannotUnmuteTarget {
            get {
                return ResourceManager.GetString("UserCannotUnmuteTarget", resourceCulture);
            }
        }

        internal static string EventEarlyNotification {
            get {
                return ResourceManager.GetString("EventEarlyNotification", resourceCulture);
            }
        }

        internal static string SettingsEventEarlyNotificationOffset {
            get {
                return ResourceManager.GetString("SettingsEventEarlyNotificationOffset", resourceCulture);
            }
        }

        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }

        internal static string SettingsDefaultRole {
            get {
                return ResourceManager.GetString("SettingsDefaultRole", resourceCulture);
            }
        }

        internal static string SettingsPublicFeedbackChannel {
            get {
                return ResourceManager.GetString("SettingsPublicFeedbackChannel", resourceCulture);
            }
        }

        internal static string SettingsPrivateFeedbackChannel {
            get {
                return ResourceManager.GetString("SettingsPrivateFeedbackChannel", resourceCulture);
            }
        }

        internal static string SettingsReturnRolesOnRejoin {
            get {
                return ResourceManager.GetString("SettingsReturnRolesOnRejoin", resourceCulture);
            }
        }

        internal static string SettingsAutoStartEvents {
            get {
                return ResourceManager.GetString("SettingsAutoStartEvents", resourceCulture);
            }
        }

        internal static string IssuedBy {
            get {
                return ResourceManager.GetString("IssuedBy", resourceCulture);
            }
        }

        internal static string EventCreatedTitle {
            get {
                return ResourceManager.GetString("EventCreatedTitle", resourceCulture);
            }
        }

        internal static string DescriptionLocalEventCreated {
            get {
                return ResourceManager.GetString("DescriptionLocalEventCreated", resourceCulture);
            }
        }

        internal static string DescriptionExternalEventCreated {
            get {
                return ResourceManager.GetString("DescriptionExternalEventCreated", resourceCulture);
            }
        }

        internal static string ButtonOpenEventInfo {
            get {
                return ResourceManager.GetString("ButtonOpenEventInfo", resourceCulture);
            }
        }

        internal static string EventDuration {
            get {
                return ResourceManager.GetString("EventDuration", resourceCulture);
            }
        }

        internal static string DescriptionLocalEventStarted {
            get {
                return ResourceManager.GetString("DescriptionLocalEventStarted", resourceCulture);
            }
        }

        internal static string DescriptionExternalEventStarted {
            get {
                return ResourceManager.GetString("DescriptionExternalEventStarted", resourceCulture);
            }
        }

        internal static string UserAlreadyBanned {
            get {
                return ResourceManager.GetString("UserAlreadyBanned", resourceCulture);
            }
        }

        internal static string UserUnbanned {
            get {
                return ResourceManager.GetString("UserUnbanned", resourceCulture);
            }
        }

        internal static string UserMuted {
            get {
                return ResourceManager.GetString("UserMuted", resourceCulture);
            }
        }

        internal static string UserUnmuted {
            get {
                return ResourceManager.GetString("UserUnmuted", resourceCulture);
            }
        }

        internal static string UserNotMuted {
            get {
                return ResourceManager.GetString("UserNotMuted", resourceCulture);
            }
        }

        internal static string UserNotFoundShort {
            get {
                return ResourceManager.GetString("UserNotFoundShort", resourceCulture);
            }
        }

        internal static string UserKicked {
            get {
                return ResourceManager.GetString("UserKicked", resourceCulture);
            }
        }

        internal static string DescriptionActionReason {
            get {
                return ResourceManager.GetString("DescriptionActionReason", resourceCulture);
            }
        }

        internal static string DescriptionActionExpiresAt {
            get {
                return ResourceManager.GetString("DescriptionActionExpiresAt", resourceCulture);
            }
        }

        internal static string UserAlreadyMuted {
            get {
                return ResourceManager.GetString("UserAlreadyMuted", resourceCulture);
            }
        }

        internal static string MessageFrom {
            get {
                return ResourceManager.GetString("MessageFrom", resourceCulture);
            }
        }

        internal static string AboutTitleDevelopers {
            get {
                return ResourceManager.GetString("AboutTitleDevelopers", resourceCulture);
            }
        }

        internal static string ButtonOpenRepository {
            get {
                return ResourceManager.GetString("ButtonOpenRepository", resourceCulture);
            }
        }

        internal static string AboutBot {
            get {
                return ResourceManager.GetString("AboutBot", resourceCulture);
            }
        }

        internal static string AboutDeveloper_mctaylors {
            get {
                return ResourceManager.GetString("AboutDeveloper@mctaylors", resourceCulture);
            }
        }

        internal static string AboutDeveloper_Octol1ttle {
            get {
                return ResourceManager.GetString("AboutDeveloper@Octol1ttle", resourceCulture);
            }
        }

        internal static string AboutDeveloper_neroduckale {
            get {
                return ResourceManager.GetString("AboutDeveloper@neroduckale", resourceCulture);
            }
        }

        internal static string ReminderCreated {
            get {
                return ResourceManager.GetString("ReminderCreated", resourceCulture);
            }
        }

        internal static string Reminder {
            get {
                return ResourceManager.GetString("Reminder", resourceCulture);
            }
        }

        internal static string DescriptionReminder {
            get {
                return ResourceManager.GetString("DescriptionReminder", resourceCulture);
            }
        }

        internal static string SettingsListTitle {
            get {
                return ResourceManager.GetString("SettingsListTitle", resourceCulture);
            }
        }

        internal static string SettingSuccessfullyChanged {
            get {
                return ResourceManager.GetString("SettingSuccessfullyChanged", resourceCulture);
            }
        }

        internal static string SettingNotChanged {
            get {
                return ResourceManager.GetString("SettingNotChanged", resourceCulture);
            }
        }

        internal static string SettingIsNow {
            get {
                return ResourceManager.GetString("SettingIsNow", resourceCulture);
            }
        }

        internal static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }

        internal static string PageNotFound {
            get {
                return ResourceManager.GetString("PageNotFound", resourceCulture);
            }
        }

        internal static string PagesAllowed {
            get {
                return ResourceManager.GetString("PagesAllowed", resourceCulture);
            }
        }

        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }

        internal static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }

        internal static string ReminderList {
            get {
                return ResourceManager.GetString("ReminderList", resourceCulture);
            }
        }

        internal static string InvalidReminderPosition {
            get {
                return ResourceManager.GetString("InvalidReminderPosition", resourceCulture);
            }
        }

        internal static string ReminderDeleted {
            get {
                return ResourceManager.GetString("ReminderDeleted", resourceCulture);
            }
        }

        internal static string NoRemindersFound {
            get {
                return ResourceManager.GetString("NoRemindersFound", resourceCulture);
            }
        }

        internal static string SingleSettingReset {
            get {
                return ResourceManager.GetString("SingleSettingReset", resourceCulture);
            }
        }

        internal static string AllSettingsReset {
            get {
                return ResourceManager.GetString("AllSettingsReset", resourceCulture);
            }
        }

        internal static string DescriptionActionJumpToMessage {
            get {
                return ResourceManager.GetString("DescriptionActionJumpToMessage", resourceCulture);
            }
        }

        internal static string DescriptionActionJumpToChannel {
            get {
                return ResourceManager.GetString("DescriptionActionJumpToChannel", resourceCulture);
            }
        }

        internal static string ReminderPosition {
            get {
                return ResourceManager.GetString("ReminderPosition", resourceCulture);
            }
        }

        internal static string ReminderTime {
            get {
                return ResourceManager.GetString("ReminderTime", resourceCulture);
            }
        }

        internal static string ReminderText {
            get {
                return ResourceManager.GetString("ReminderText", resourceCulture);
            }
        }

        internal static string InformationAbout {
            get {
                return ResourceManager.GetString("InformationAbout", resourceCulture);
            }
        }

        internal static string UserInfoDisplayName {
            get {
                return ResourceManager.GetString("UserInfoDisplayName", resourceCulture);
            }
        }

        internal static string UserInfoDiscordUserSince {
            get {
                return ResourceManager.GetString("UserInfoDiscordUserSince", resourceCulture);
            }
        }

        internal static string UserInfoMuted {
            get {
                return ResourceManager.GetString("UserInfoMuted", resourceCulture);
            }
        }

        internal static string UserInfoBanned {
            get {
                return ResourceManager.GetString("UserInfoBanned", resourceCulture);
            }
        }

        internal static string UserInfoPunishments {
            get {
                return ResourceManager.GetString("UserInfoPunishments", resourceCulture);
            }
        }

        internal static string UserInfoBannedPermanently {
            get {
                return ResourceManager.GetString("UserInfoBannedPermanently", resourceCulture);
            }
        }

        internal static string UserInfoNotOnGuild {
            get {
                return ResourceManager.GetString("UserInfoNotOnGuild", resourceCulture);
            }
        }

        internal static string UserInfoMutedByTimeout {
            get {
                return ResourceManager.GetString("UserInfoMutedByTimeout", resourceCulture);
            }
        }

        internal static string UserInfoMutedByMuteRole {
            get {
                return ResourceManager.GetString("UserInfoMutedByMuteRole", resourceCulture);
            }
        }

        internal static string UserInfoGuildMemberSince {
            get {
                return ResourceManager.GetString("UserInfoGuildMemberSince", resourceCulture);
            }
        }

        internal static string UserInfoGuildNickname {
            get {
                return ResourceManager.GetString("UserInfoGuildNickname", resourceCulture);
            }
        }

        internal static string UserInfoGuildRoles {
            get {
                return ResourceManager.GetString("UserInfoGuildRoles", resourceCulture);
            }
        }

        internal static string UserInfoGuildMemberPremiumSince {
            get {
                return ResourceManager.GetString("UserInfoGuildMemberPremiumSince", resourceCulture);
            }
        }

        internal static string RandomTitle
        {
            get {
                return ResourceManager.GetString("RandomTitle", resourceCulture);
            }
        }

        internal static string RandomMinMaxSame
        {
            get {
                return ResourceManager.GetString("RandomMinMaxSame", resourceCulture);
            }
        }

        internal static string RandomMax
        {
            get {
                return ResourceManager.GetString("RandomMax", resourceCulture);
            }
        }

        internal static string RandomMin
        {
            get {
                return ResourceManager.GetString("RandomMin", resourceCulture);
            }
        }

        internal static string Default
        {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }

        internal static string TimestampTitle
        {
            get
            {
                return ResourceManager.GetString("TimestampTitle", resourceCulture);
            }
        }

        internal static string TimestampOffset
        {
            get
            {
                return ResourceManager.GetString("TimestampOffset", resourceCulture);
            }
        }

        internal static string GuildInfoDescription
        {
            get
            {
                return ResourceManager.GetString("GuildInfoDescription", resourceCulture);
            }
        }

        internal static string GuildInfoCreatedAt
        {
            get
            {
                return ResourceManager.GetString("GuildInfoCreatedAt", resourceCulture);
            }
        }

        internal static string GuildInfoOwner
        {
            get
            {
                return ResourceManager.GetString("GuildInfoOwner", resourceCulture);
            }
        }

        internal static string GuildInfoServerBoost
        {
            get
            {
                return ResourceManager.GetString("GuildInfoServerBoost", resourceCulture);
            }
        }

        internal static string GuildInfoBoostTier
        {
            get
            {
                return ResourceManager.GetString("GuildInfoBoostTier", resourceCulture);
            }
        }

        internal static string GuildInfoBoostCount
        {
            get
            {
                return ResourceManager.GetString("GuildInfoBoostCount", resourceCulture);
            }
        }

        internal static string NoMessagesToClear
        {
            get
            {
                return ResourceManager.GetString("NoMessagesToClear", resourceCulture);
            }
        }

        internal static string MessagesClearedFiltered
        {
            get
            {
                return ResourceManager.GetString("MessagesClearedFiltered", resourceCulture);
            }
        }

        internal static string DataLoadFailedTitle
        {
            get
            {
                return ResourceManager.GetString("DataLoadFailedTitle", resourceCulture);
            }
        }

        internal static string DataLoadFailedDescription
        {
            get
            {
                return ResourceManager.GetString("DataLoadFailedDescription", resourceCulture);
            }
        }

        internal static string CommandExecutionFailed
        {
            get
            {
                return ResourceManager.GetString("CommandExecutionFailed", resourceCulture);
            }
        }

        internal static string ContactDevelopers
        {
            get
            {
                return ResourceManager.GetString("ContactDevelopers", resourceCulture);
            }
        }

        internal static string ButtonReportIssue
        {
            get
            {
                return ResourceManager.GetString("ButtonReportIssue", resourceCulture);
            }
        }

        internal static string InvalidTimeSpan
        {
            get
            {
                return ResourceManager.GetString("InvalidTimeSpan", resourceCulture);
            }
        }

        internal static string UserInfoKicked
        {
            get
            {
                return ResourceManager.GetString("UserInfoKicked", resourceCulture);
            }
        }

        internal static string ReminderEdited {
            get {
                return ResourceManager.GetString("ReminderEdited", resourceCulture);
            }
        }

        internal static string EightBallPositive1 {
            get {
                return ResourceManager.GetString("EightBallPositive1", resourceCulture);
            }
        }

        internal static string EightBallPositive2 {
            get {
                return ResourceManager.GetString("EightBallPositive2", resourceCulture);
            }
        }

        internal static string EightBallPositive3 {
            get {
                return ResourceManager.GetString("EightBallPositive3", resourceCulture);
            }
        }

        internal static string EightBallPositive4 {
            get {
                return ResourceManager.GetString("EightBallPositive4", resourceCulture);
            }
        }

        internal static string EightBallPositive5 {
            get {
                return ResourceManager.GetString("EightBallPositive5", resourceCulture);
            }
        }

        internal static string EightBallQuestionable1 {
            get {
                return ResourceManager.GetString("EightBallQuestionable1", resourceCulture);
            }
        }

        internal static string EightBallQuestionable2 {
            get {
                return ResourceManager.GetString("EightBallQuestionable2", resourceCulture);
            }
        }

        internal static string EightBallQuestionable3 {
            get {
                return ResourceManager.GetString("EightBallQuestionable3", resourceCulture);
            }
        }

        internal static string EightBallQuestionable4 {
            get {
                return ResourceManager.GetString("EightBallQuestionable4", resourceCulture);
            }
        }

        internal static string EightBallQuestionable5 {
            get {
                return ResourceManager.GetString("EightBallQuestionable5", resourceCulture);
            }
        }

        internal static string EightBallNeutral1 {
            get {
                return ResourceManager.GetString("EightBallNeutral1", resourceCulture);
            }
        }

        internal static string EightBallNeutral2 {
            get {
                return ResourceManager.GetString("EightBallNeutral2", resourceCulture);
            }
        }

        internal static string EightBallNeutral3 {
            get {
                return ResourceManager.GetString("EightBallNeutral3", resourceCulture);
            }
        }

        internal static string EightBallNeutral4 {
            get {
                return ResourceManager.GetString("EightBallNeutral4", resourceCulture);
            }
        }

        internal static string EightBallNeutral5 {
            get {
                return ResourceManager.GetString("EightBallNeutral5", resourceCulture);
            }
        }

        internal static string EightBallNegative1 {
            get {
                return ResourceManager.GetString("EightBallNegative1", resourceCulture);
            }
        }

        internal static string EightBallNegative2 {
            get {
                return ResourceManager.GetString("EightBallNegative2", resourceCulture);
            }
        }

        internal static string EightBallNegative3 {
            get {
                return ResourceManager.GetString("EightBallNegative3", resourceCulture);
            }
        }

        internal static string EightBallNegative4 {
            get {
                return ResourceManager.GetString("EightBallNegative4", resourceCulture);
            }
        }

        internal static string EightBallNegative5 {
            get {
                return ResourceManager.GetString("EightBallNegative5", resourceCulture);
            }
        }

        internal static string TimeSpanExample {
            get {
                return ResourceManager.GetString("TimeSpanExample", resourceCulture);
            }
        }

        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
