//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boyfriend {
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Boyfriend.locale.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }

        internal static string CachedMessageDeleted {
            get {
                return ResourceManager.GetString("CachedMessageDeleted", resourceCulture);
            }
        }

        internal static string CachedMessageCleared {
            get {
                return ResourceManager.GetString("CachedMessageCleared", resourceCulture);
            }
        }

        internal static string CachedMessageEdited {
            get {
                return ResourceManager.GetString("CachedMessageEdited", resourceCulture);
            }
        }

        internal static string DefaultWelcomeMessage {
            get {
                return ResourceManager.GetString("DefaultWelcomeMessage", resourceCulture);
            }
        }

        internal static string Beep1 {
            get {
                return ResourceManager.GetString("Beep1", resourceCulture);
            }
        }

        internal static string Beep2 {
            get {
                return ResourceManager.GetString("Beep2", resourceCulture);
            }
        }

        internal static string Beep3 {
            get {
                return ResourceManager.GetString("Beep3", resourceCulture);
            }
        }

        internal static string CommandNoPermissionBot {
            get {
                return ResourceManager.GetString("CommandNoPermissionBot", resourceCulture);
            }
        }

        internal static string CommandNoPermissionUser {
            get {
                return ResourceManager.GetString("CommandNoPermissionUser", resourceCulture);
            }
        }

        internal static string YouWereBanned {
            get {
                return ResourceManager.GetString("YouWereBanned", resourceCulture);
            }
        }

        internal static string PunishmentExpired {
            get {
                return ResourceManager.GetString("PunishmentExpired", resourceCulture);
            }
        }

        internal static string ClearAmountTooSmall {
            get {
                return ResourceManager.GetString("ClearAmountTooSmall", resourceCulture);
            }
        }

        internal static string ClearAmountTooLarge {
            get {
                return ResourceManager.GetString("ClearAmountTooLarge", resourceCulture);
            }
        }

        internal static string CommandHelp {
            get {
                return ResourceManager.GetString("CommandHelp", resourceCulture);
            }
        }

        internal static string YouWereKicked {
            get {
                return ResourceManager.GetString("YouWereKicked", resourceCulture);
            }
        }

        internal static string Milliseconds {
            get {
                return ResourceManager.GetString("Milliseconds", resourceCulture);
            }
        }

        internal static string MemberAlreadyMuted {
            get {
                return ResourceManager.GetString("MemberAlreadyMuted", resourceCulture);
            }
        }

        internal static string ChannelNotSpecified {
            get {
                return ResourceManager.GetString("ChannelNotSpecified", resourceCulture);
            }
        }

        internal static string RoleNotSpecified {
            get {
                return ResourceManager.GetString("RoleNotSpecified", resourceCulture);
            }
        }

        internal static string CurrentSettings {
            get {
                return ResourceManager.GetString("CurrentSettings", resourceCulture);
            }
        }

        internal static string SettingsLang {
            get {
                return ResourceManager.GetString("SettingsLang", resourceCulture);
            }
        }

        internal static string SettingsPrefix {
            get {
                return ResourceManager.GetString("SettingsPrefix", resourceCulture);
            }
        }

        internal static string SettingsRemoveRolesOnMute {
            get {
                return ResourceManager.GetString("SettingsRemoveRolesOnMute", resourceCulture);
            }
        }

        internal static string SettingsSendWelcomeMessages {
            get {
                return ResourceManager.GetString("SettingsSendWelcomeMessages", resourceCulture);
            }
        }

        internal static string SettingsMuteRole {
            get {
                return ResourceManager.GetString("SettingsMuteRole", resourceCulture);
            }
        }

        internal static string LanguageNotSupported {
            get {
                return ResourceManager.GetString("LanguageNotSupported", resourceCulture);
            }
        }

        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }

        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }

        internal static string UserNotBanned {
            get {
                return ResourceManager.GetString("UserNotBanned", resourceCulture);
            }
        }

        internal static string MemberNotMuted {
            get {
                return ResourceManager.GetString("MemberNotMuted", resourceCulture);
            }
        }

        internal static string SettingsWelcomeMessage {
            get {
                return ResourceManager.GetString("SettingsWelcomeMessage", resourceCulture);
            }
        }

        internal static string ClearAmountInvalid {
            get {
                return ResourceManager.GetString("ClearAmountInvalid", resourceCulture);
            }
        }

        internal static string UserBanned {
            get {
                return ResourceManager.GetString("UserBanned", resourceCulture);
            }
        }

        internal static string SettingDoesntExist {
            get {
                return ResourceManager.GetString("SettingDoesntExist", resourceCulture);
            }
        }

        internal static string SettingsReceiveStartupMessages {
            get {
                return ResourceManager.GetString("SettingsReceiveStartupMessages", resourceCulture);
            }
        }

        internal static string InvalidSettingValue {
            get {
                return ResourceManager.GetString("InvalidSettingValue", resourceCulture);
            }
        }

        internal static string InvalidRole {
            get {
                return ResourceManager.GetString("InvalidRole", resourceCulture);
            }
        }

        internal static string InvalidChannel {
            get {
                return ResourceManager.GetString("InvalidChannel", resourceCulture);
            }
        }

        internal static string DurationRequiredForTimeOuts {
            get {
                return ResourceManager.GetString("DurationRequiredForTimeOuts", resourceCulture);
            }
        }

        internal static string CannotTimeOutBot {
            get {
                return ResourceManager.GetString("CannotTimeOutBot", resourceCulture);
            }
        }

        internal static string EventCreated {
            get {
                return ResourceManager.GetString("EventCreated", resourceCulture);
            }
        }

        internal static string SettingsEventNotificationRole {
            get {
                return ResourceManager.GetString("SettingsEventNotificationRole", resourceCulture);
            }
        }

        internal static string SettingsEventNotificationChannel {
            get {
                return ResourceManager.GetString("SettingsEventNotificationChannel", resourceCulture);
            }
        }

        internal static string SettingsEventStartedReceivers {
            get {
                return ResourceManager.GetString("SettingsEventStartedReceivers", resourceCulture);
            }
        }

        internal static string EventStarted {
            get {
                return ResourceManager.GetString("EventStarted", resourceCulture);
            }
        }

        internal static string SettingsFrowningFace {
            get {
                return ResourceManager.GetString("SettingsFrowningFace", resourceCulture);
            }
        }

        internal static string EventCancelled {
            get {
                return ResourceManager.GetString("EventCancelled", resourceCulture);
            }
        }

        internal static string EventCompleted {
            get {
                return ResourceManager.GetString("EventCompleted", resourceCulture);
            }
        }

        internal static string Ever {
            get {
                return ResourceManager.GetString("Ever", resourceCulture);
            }
        }

        internal static string MessagesCleared {
            get {
                return ResourceManager.GetString("MessagesCleared", resourceCulture);
            }
        }

        internal static string FeedbackMemberKicked {
            get {
                return ResourceManager.GetString("FeedbackMemberKicked", resourceCulture);
            }
        }

        internal static string FeedbackMemberMuted {
            get {
                return ResourceManager.GetString("FeedbackMemberMuted", resourceCulture);
            }
        }

        internal static string FeedbackUserUnbanned {
            get {
                return ResourceManager.GetString("FeedbackUserUnbanned", resourceCulture);
            }
        }

        internal static string FeedbackMemberUnmuted {
            get {
                return ResourceManager.GetString("FeedbackMemberUnmuted", resourceCulture);
            }
        }

        internal static string SettingsNothingChanged {
            get {
                return ResourceManager.GetString("SettingsNothingChanged", resourceCulture);
            }
        }

        internal static string SettingNotDefined {
            get {
                return ResourceManager.GetString("SettingNotDefined", resourceCulture);
            }
        }

        internal static string FeedbackSettingsUpdated {
            get {
                return ResourceManager.GetString("FeedbackSettingsUpdated", resourceCulture);
            }
        }

        internal static string CommandDescriptionBan {
            get {
                return ResourceManager.GetString("CommandDescriptionBan", resourceCulture);
            }
        }

        internal static string CommandDescriptionClear {
            get {
                return ResourceManager.GetString("CommandDescriptionClear", resourceCulture);
            }
        }

        internal static string CommandDescriptionHelp {
            get {
                return ResourceManager.GetString("CommandDescriptionHelp", resourceCulture);
            }
        }

        internal static string CommandDescriptionKick {
            get {
                return ResourceManager.GetString("CommandDescriptionKick", resourceCulture);
            }
        }

        internal static string CommandDescriptionMute {
            get {
                return ResourceManager.GetString("CommandDescriptionMute", resourceCulture);
            }
        }

        internal static string CommandDescriptionPing {
            get {
                return ResourceManager.GetString("CommandDescriptionPing", resourceCulture);
            }
        }

        internal static string CommandDescriptionSettings {
            get {
                return ResourceManager.GetString("CommandDescriptionSettings", resourceCulture);
            }
        }

        internal static string CommandDescriptionUnban {
            get {
                return ResourceManager.GetString("CommandDescriptionUnban", resourceCulture);
            }
        }

        internal static string CommandDescriptionUnmute {
            get {
                return ResourceManager.GetString("CommandDescriptionUnmute", resourceCulture);
            }
        }

        internal static string MissingNumber {
            get {
                return ResourceManager.GetString("MissingNumber", resourceCulture);
            }
        }

        internal static string MissingUser {
            get {
                return ResourceManager.GetString("MissingUser", resourceCulture);
            }
        }

        internal static string InvalidUser {
            get {
                return ResourceManager.GetString("InvalidUser", resourceCulture);
            }
        }

        internal static string MissingMember {
            get {
                return ResourceManager.GetString("MissingMember", resourceCulture);
            }
        }

        internal static string InvalidMember {
            get {
                return ResourceManager.GetString("InvalidMember", resourceCulture);
            }
        }

        internal static string UserCannotBanMembers {
            get {
                return ResourceManager.GetString("UserCannotBanMembers", resourceCulture);
            }
        }

        internal static string UserCannotManageMessages {
            get {
                return ResourceManager.GetString("UserCannotManageMessages", resourceCulture);
            }
        }

        internal static string UserCannotKickMembers {
            get {
                return ResourceManager.GetString("UserCannotKickMembers", resourceCulture);
            }
        }

        internal static string UserCannotModerateMembers {
            get {
                return ResourceManager.GetString("UserCannotModerateMembers", resourceCulture);
            }
        }

        internal static string UserCannotManageGuild {
            get {
                return ResourceManager.GetString("UserCannotManageGuild", resourceCulture);
            }
        }

        internal static string BotCannotBanMembers {
            get {
                return ResourceManager.GetString("BotCannotBanMembers", resourceCulture);
            }
        }

        internal static string BotCannotManageMessages {
            get {
                return ResourceManager.GetString("BotCannotManageMessages", resourceCulture);
            }
        }

        internal static string BotCannotKickMembers {
            get {
                return ResourceManager.GetString("BotCannotKickMembers", resourceCulture);
            }
        }

        internal static string BotCannotModerateMembers {
            get {
                return ResourceManager.GetString("BotCannotModerateMembers", resourceCulture);
            }
        }

        internal static string BotCannotManageGuild {
            get {
                return ResourceManager.GetString("BotCannotManageGuild", resourceCulture);
            }
        }

        internal static string MissingBanReason {
            get {
                return ResourceManager.GetString("MissingBanReason", resourceCulture);
            }
        }

        internal static string MissingKickReason {
            get {
                return ResourceManager.GetString("MissingKickReason", resourceCulture);
            }
        }

        internal static string MissingMuteReason {
            get {
                return ResourceManager.GetString("MissingMuteReason", resourceCulture);
            }
        }

        internal static string MissingUnbanReason {
            get {
                return ResourceManager.GetString("MissingUnbanReason", resourceCulture);
            }
        }

        internal static string MissingUnmuteReason {
            get {
                return ResourceManager.GetString("MissingUnmuteReason", resourceCulture);
            }
        }

        internal static string UserCannotBanOwner {
            get {
                return ResourceManager.GetString("UserCannotBanOwner", resourceCulture);
            }
        }

        internal static string UserCannotBanThemselves {
            get {
                return ResourceManager.GetString("UserCannotBanThemselves", resourceCulture);
            }
        }

        internal static string UserCannotBanBot {
            get {
                return ResourceManager.GetString("UserCannotBanBot", resourceCulture);
            }
        }

        internal static string BotCannotBanTarget {
            get {
                return ResourceManager.GetString("BotCannotBanTarget", resourceCulture);
            }
        }

        internal static string UserCannotBanTarget {
            get {
                return ResourceManager.GetString("UserCannotBanTarget", resourceCulture);
            }
        }

        internal static string UserCannotKickOwner {
            get {
                return ResourceManager.GetString("UserCannotKickOwner", resourceCulture);
            }
        }

        internal static string UserCannotKickThemselves {
            get {
                return ResourceManager.GetString("UserCannotKickThemselves", resourceCulture);
            }
        }

        internal static string UserCannotKickBot {
            get {
                return ResourceManager.GetString("UserCannotKickBot", resourceCulture);
            }
        }

        internal static string BotCannotKickTarget {
            get {
                return ResourceManager.GetString("BotCannotKickTarget", resourceCulture);
            }
        }

        internal static string UserCannotKickTarget {
            get {
                return ResourceManager.GetString("UserCannotKickTarget", resourceCulture);
            }
        }

        internal static string UserCannotMuteOwner {
            get {
                return ResourceManager.GetString("UserCannotMuteOwner", resourceCulture);
            }
        }

        internal static string UserCannotMuteThemselves {
            get {
                return ResourceManager.GetString("UserCannotMuteThemselves", resourceCulture);
            }
        }

        internal static string UserCannotMuteBot {
            get {
                return ResourceManager.GetString("UserCannotMuteBot", resourceCulture);
            }
        }

        internal static string BotCannotMuteTarget {
            get {
                return ResourceManager.GetString("BotCannotMuteTarget", resourceCulture);
            }
        }

        internal static string UserCannotMuteTarget {
            get {
                return ResourceManager.GetString("UserCannotMuteTarget", resourceCulture);
            }
        }

        internal static string UserCannotUnmuteOwner {
            get {
                return ResourceManager.GetString("UserCannotUnmuteOwner", resourceCulture);
            }
        }

        internal static string UserCannotUnmuteThemselves {
            get {
                return ResourceManager.GetString("UserCannotUnmuteThemselves", resourceCulture);
            }
        }

        internal static string UserCannotUnmuteBot {
            get {
                return ResourceManager.GetString("UserCannotUnmuteBot", resourceCulture);
            }
        }

        internal static string BotCannotUnmuteTarget {
            get {
                return ResourceManager.GetString("BotCannotUnmuteTarget", resourceCulture);
            }
        }

        internal static string UserCannotUnmuteTarget {
            get {
                return ResourceManager.GetString("UserCannotUnmuteTarget", resourceCulture);
            }
        }

        internal static string EventEarlyNotification {
            get {
                return ResourceManager.GetString("EventEarlyNotification", resourceCulture);
            }
        }

        internal static string SettingsEventEarlyNotificationOffset {
            get {
                return ResourceManager.GetString("SettingsEventEarlyNotificationOffset", resourceCulture);
            }
        }

        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }

        internal static string SettingsDefaultRole {
            get {
                return ResourceManager.GetString("SettingsDefaultRole", resourceCulture);
            }
        }

        internal static string CommandDescriptionRemind {
            get {
                return ResourceManager.GetString("CommandDescriptionRemind", resourceCulture);
            }
        }

        internal static string SettingsPublicFeedbackChannel {
            get {
                return ResourceManager.GetString("SettingsPublicFeedbackChannel", resourceCulture);
            }
        }

        internal static string SettingsPrivateFeedbackChannel {
            get {
                return ResourceManager.GetString("SettingsPrivateFeedbackChannel", resourceCulture);
            }
        }

        internal static string SettingsReturnRolesOnRejoin {
            get {
                return ResourceManager.GetString("SettingsReturnRolesOnRejoin", resourceCulture);
            }
        }

        internal static string SettingsAutoStartEvents {
            get {
                return ResourceManager.GetString("SettingsAutoStartEvents", resourceCulture);
            }
        }

        internal static string MissingReminderText {
            get {
                return ResourceManager.GetString("MissingReminderText", resourceCulture);
            }
        }

        internal static string DescriptionReminderCreated {
            get {
                return ResourceManager.GetString("DescriptionReminderCreated", resourceCulture);
            }
        }

        internal static string InvalidRemindIn {
            get {
                return ResourceManager.GetString("InvalidRemindIn", resourceCulture);
            }
        }

        internal static string IssuedBy {
            get {
                return ResourceManager.GetString("IssuedBy", resourceCulture);
            }
        }

        internal static string EventCreatedTitle {
            get {
                return ResourceManager.GetString("EventCreatedTitle", resourceCulture);
            }
        }

        internal static string DescriptionLocalEventCreated {
            get {
                return ResourceManager.GetString("DescriptionLocalEventCreated", resourceCulture);
            }
        }

        internal static string DescriptionExternalEventCreated {
            get {
                return ResourceManager.GetString("DescriptionExternalEventCreated", resourceCulture);
            }
        }

        internal static string EventDetailsButton {
            get {
                return ResourceManager.GetString("EventDetailsButton", resourceCulture);
            }
        }

        internal static string EventDuration {
            get {
                return ResourceManager.GetString("EventDuration", resourceCulture);
            }
        }

        internal static string DescriptionLocalEventStarted {
            get {
                return ResourceManager.GetString("DescriptionLocalEventStarted", resourceCulture);
            }
        }

        internal static string DescriptionExternalEventStarted {
            get {
                return ResourceManager.GetString("DescriptionExternalEventStarted", resourceCulture);
            }
        }

        internal static string UserAlreadyBanned {
            get {
                return ResourceManager.GetString("UserAlreadyBanned", resourceCulture);
            }
        }

        internal static string UserUnbanned {
            get {
                return ResourceManager.GetString("UserUnbanned", resourceCulture);
            }
        }

        internal static string UserMuted {
            get {
                return ResourceManager.GetString("UserMuted", resourceCulture);
            }
        }

        internal static string UserUnmuted {
            get {
                return ResourceManager.GetString("UserUnmuted", resourceCulture);
            }
        }

        internal static string UserNotMuted {
            get {
                return ResourceManager.GetString("UserNotMuted", resourceCulture);
            }
        }

        internal static string UserNotFoundShort {
            get {
                return ResourceManager.GetString("UserNotFoundShort", resourceCulture);
            }
        }

        internal static string UserKicked {
            get {
                return ResourceManager.GetString("UserKicked", resourceCulture);
            }
        }

        internal static string DescriptionActionReason {
            get {
                return ResourceManager.GetString("DescriptionActionReason", resourceCulture);
            }
        }

        internal static string DescriptionActionExpiresAt {
            get {
                return ResourceManager.GetString("DescriptionActionExpiresAt", resourceCulture);
            }
        }

        internal static string UserAlreadyMuted {
            get {
                return ResourceManager.GetString("UserAlreadyMuted", resourceCulture);
            }
        }

        internal static string MessageFrom {
            get {
                return ResourceManager.GetString("MessageFrom", resourceCulture);
            }
        }

        internal static string AboutTitleDevelopers {
            get {
                return ResourceManager.GetString("AboutTitleDevelopers", resourceCulture);
            }
        }

        internal static string AboutTitleWiki {
            get {
                return ResourceManager.GetString("AboutTitleWiki", resourceCulture);
            }
        }

        internal static string AboutBot {
            get {
                return ResourceManager.GetString("AboutBot", resourceCulture);
            }
        }

        internal static string AboutDeveloper_mctaylors {
            get {
                return ResourceManager.GetString("AboutDeveloper@mctaylors", resourceCulture);
            }
        }

        internal static string AboutDeveloper_Octol1ttle {
            get {
                return ResourceManager.GetString("AboutDeveloper@Octol1ttle", resourceCulture);
            }
        }

        internal static string AboutDeveloper_neroduckale {
            get {
                return ResourceManager.GetString("AboutDeveloper@neroduckale", resourceCulture);
            }
        }

        internal static string ReminderCreated {
            get {
                return ResourceManager.GetString("ReminderCreated", resourceCulture);
            }
        }

        internal static string Reminder {
            get {
                return ResourceManager.GetString("Reminder", resourceCulture);
            }
        }

        internal static string DescriptionReminder {
            get {
                return ResourceManager.GetString("DescriptionReminder", resourceCulture);
            }
        }

        internal static string SettingsListTitle {
            get {
                return ResourceManager.GetString("SettingsListTitle", resourceCulture);
            }
        }

        internal static string SettingSuccessfullyChanged {
            get {
                return ResourceManager.GetString("SettingSuccessfullyChanged", resourceCulture);
            }
        }

        internal static string SettingNotChanged {
            get {
                return ResourceManager.GetString("SettingNotChanged", resourceCulture);
            }
        }

        internal static string SettingIsNow {
            get {
                return ResourceManager.GetString("SettingIsNow", resourceCulture);
            }
        }

        internal static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }

        internal static string PageNotFound {
            get {
                return ResourceManager.GetString("PageNotFound", resourceCulture);
            }
        }

        internal static string PagesAllowed {
            get {
                return ResourceManager.GetString("PagesAllowed", resourceCulture);
            }
        }

        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }

        internal static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
    }
}
